services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    hostname: glance
    healthcheck:
      test: curl -Lk -fsS http://localhost:8082 || exit 1
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - ./glance.yml:/app/config/glance.yml
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - red-servicios

networks:
  red-servicios:
    external: true
