services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run --config /config/adguardhome-sync.yaml
    environment:
      TZ: Europe/Madrid
      LOG_LEVEL: info
      ORIGIN_URL: http://10.10.100.23
      ORIGIN_USERNAME: 
      ORIGIN_PASSWORD: 
      REPLICA1_URL: http://10.10.100.20
      REPLICA1_USERNAME: 
      REPLICA1_PASSWORD: 
      CRON: "*/10 * * * *" # 10 minutos
      RUN_ON_START: "true"
      API_PORT: 8081
    ports:
      - 8081:8081
    restart: unless-stopped
  jellyplex-watched:
    image: ghcr.io/luigi311/jellyplex-watched:latest
    container_name: jellyplex-watched
    restart: unless-stopped
    environment:
      TZ: Europe/Madrid
      DRYRUN: "False" # 1ª corrida en modo simulación. Cambia a "False" cuando verifiques.
      DEBUG_LEVEL: INFO # "DEBUG" si necesitas ver matching en detalle
      RUN_ONLY_ONCE: "False" # "False" = modo daemon (loop); "True" = una pasada y sale
      SLEEP_DURATION: "600" # cada 10 min.
      LOG_FILE: log.log
      MARK_FILE: mark.log
      REQUEST_TIMEOUT: 300
      MAX_THREADS: 4
      GENERATE_GUIDS: "True"
      GENERATE_LOCATIONS: "True"
      USER_MAPPING: '{ "yraedry": "Mayden" }'
      LIBRARY_MAPPING: '{ "Shows": "Series", "Movie": "Peliculas" }'
      PLEX_BASEURL: http://10.10.100.25:32400
      PLEX_TOKEN: 
      SSL_BYPASS: "False"
      JELLYFIN_BASEURL: http://10.10.100.33:8096
      JELLYFIN_TOKEN: 
      SYNC_FROM_JELLYFIN_TO_PLEX: "True"
      SYNC_FROM_PLEX_TO_JELLYFIN: "True"
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - WATCHTOWER_LIFECYCLE_HOOKS=1
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=ntfy://notificaciones.adriannsanchez.com/docker
    command: adguardhome-sync jellyplex-watched sonarr radarr prowlarr --interval
      86400 --cleanup --debug
    restart: unless-stopped
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    hostname: npm
    healthcheck:
      test: curl -Lk -fsS http://localhost:81 || exit 1
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      - TZ=${TZ:-Etc/UTC}
      - DISABLE_IPV6="true'
    volumes:
      - ${CONFIG}/npm/data:/data
      - ${CONFIG}/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
