services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    hostname: adguardhome-sync
    healthcheck:
      test: curl -Lk -fsS http://localhost:8081 || exit 1
    environment:
      TZ: ${TZ}
      LOG_LEVEL: ${LOG_LEVEL}
      ORIGIN_URL: ${ORIGIN_URL}
      ORIGIN_USERNAME: ${ORIGIN_USERNAME}
      ORIGIN_PASSWORD: ${ORIGIN_PASSWORD}
      REPLICA1_URL:  ${REPLICA1_URL}
      REPLICA1_USERNAME: ${REPLICA1_USERNAME}
      REPLICA1_PASSWORD: ${REPLICA1_PASSWORD}
      CRON: ${CRON}
      RUN_ON_START: "true"
      API_PORT: ${API_PORT}
    ports:
      - 8081:8081
    restart: unless-stopped
    networks:
      - red-criticos

networks:
  red-criticos:
    external: true
