services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    hostname: vaultwarden
    healthcheck:
      test: curl -Lk -fsS http://localhost:80 || exit 1
    environment:
      - TZ=${TZ}
    volumes:
      - ./data:/data
    ports:
      - "8085:80"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - red-criticos

networks:
  red-criticos:
    external: true