services:
  sonarr:
    image: linuxserver/sonarr:4.0.16
    container_name: sonarr
    hostname: sonarr
    healthcheck:
      test: curl -Lk -fsS http://localhost:8989 || exit 1
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ}
      - UMASK=${UMASK:-022}
    volumes:
      - ./config:/config/:rw
      - ${UNRAID_MOUNT}:/multimedia/:rw
    ports:
      - 8989:8989/tcp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - red-arr

networks:
  red-arr:
    external: true
