services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent
    hostname: arcane-agent
    healthcheck:
      test: curl -Lk -fsS http://localhost:3553 || exit 1
    environment:
      - AGENT_MODE=true
      - AGENT_TOKEN=${AGENT_TOKEN}
      - MANAGER_API_URL=${MANAGED_API}
    ports:
      - "3553:3553"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/:/app/data/projects
      - arcane-data:/app/data
    restart: unless-stopped
